// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uxidhyfshjijemfflzie.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV4aWRoeWZzaGppamVtZmZsemllIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxODY5NzAsImV4cCI6MjA1OTc2Mjk3MH0.yE9uvUv4b0psvtr5SkDlcO1qE4q5Cgu5uMoqQypuQsU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);