
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tpdztofzznckqgejsqip.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRwZHp0b2Z6em5ja3FnZWpzcWlwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyMjI0MTUsImV4cCI6MjA1OTc5ODQxNX0.h9MFUR3m2-7tIZNyh3uUFui6j11VviR4PrkhbyTDwbg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
